name: BlzdFly
version: 1.0.3
main: com.blzd.fly.BlzdFly
api-version: '1.21'
author: Blzd
description: Custom flight management plugin with timed flight, permanent flight, claim flight, safe landing, and claim plugin integration.
softdepend:
  - GriefDefender

commands:
  fly:
    description: Manage flight
    usage: |
      /fly
      /fly info
      /fly reload
      /fly give <player> <time>
      /fly remove <player> <time>
      /fly set <player> <time>
      /fly time <player>

permissions:
  blzdfly.timed:
    description: Allows use of timed flight.
    default: false

  blzdfly.claim:
    description: Allows use of claim flight.
    default: false

  blzdfly.permanent:
    description: Allows unlimited flight.
    default: false

  blzdfly.admin:
    description: Allows access to admin commands.
    default: op
